#!/usr/bin/env php
<?php
/**
* @package     Joomla.Cli
*
 * @copyright  Copyright (C) 2005 - 2013 Open Source Matters, Inc. All rights reserved.
 * @license    GNU General Public License version 2 or later; see LICENSE.txt
*/

// We are a valid entry point.
const _JEXEC = 1;

// Configure error reporting to maximum for CLI output.
error_reporting(E_ALL);
ini_set('display_errors', 1);

// Load system defines
if (file_exists(dirname(__DIR__) . '/defines.php'))
{
	require_once dirname(__DIR__) . '/defines.php';
}

if (!defined('_JDEFINES'))
{
	define('JPATH_BASE', dirname(__DIR__));
	require_once JPATH_BASE . '/includes/defines.php';
}

// Get the framework.
require_once JPATH_BASE . '/includes/framework.php';

// Bootstrap the CMS libraries.
require_once JPATH_LIBRARIES . '/cms.php';


// Load Console libraries
JLoader::registerNamespace('Joomla',   __DIR__ . '/jconsole/vendor/framework');
JLoader::registerNamespace('JConsole', __DIR__ . '/jconsole/vendor/console');
JLoader::registerNamespace('Command',  __DIR__ . '/jconsole/src');

// If using Console, we need Psr package
JLoader::registerNamespace('Psr', __DIR__ . '/jconsole/vendor/psr');

// Import the configuration.
require_once JPATH_CONFIGURATION . '/configuration.php';

// System configuration.
$config = new JConfig;

use JConsole\Application\Console;

$console = new Console;

$console->setDescription(null)
	->execute();

exit(0);